### ISSUE TITLE
Version 1.1.0 missing lib / dist

### ISSUE THREAD

**Issue by loonpwn** [payscale/country-currency-map#23]
Looks like the version was published without the lib and dist folder included, causing any implementation on this version to break

![image](https://user-images.githubusercontent.com/5326365/65558794-6cbfee80-df7b-11e9-8f3c-c7f484dc04e8.png)

**Comment by dfenske** [comment]
I don't believe we've ever published the lib/dist folders for this package. Did you have a previous version that was working and now it doesn't?

**Comment by dfenske** [comment]
Oops I was mistaken. I understand what you mean now - we are working on a fix to make sure dist/lib get published with the npm package.

**Comment by IjzerenHein** [comment]
I'm running into this problem as well. I noticed that 1.1.3 has been released 2 days ago, but that also has missing files. v.1.13 only installs these files on my machine:

![image](https://user-images.githubusercontent.com/6184593/66118744-6f53c100-e5d7-11e9-9faf-ffaeba9cffd9.png)

**Comment by ncua** [comment]
We just published a new version today - 2.0.0 that contains the lib and dist files.

Sorry for the inconvenience!

**Comment by IjzerenHein** [comment]
Awesome, will test on Monday! Thanks for this open-source project!

**Comment by IjzerenHein** [comment]
It seems that some of the file locations have changed in the new v2 release, but apart from that everything works like a charm 👍 
Thanks!
