### ISSUE TITLE
Module not installing dependencies

### ISSUE THREAD

**Issue by ralphotowo** [payscale/country-currency-map#29]
I am attempting to use this module with Node 10.18 but the module isn't installing like the other modules defines in the **package.json** - I also tried installing it directly using `npm i country-currency` map and it only creates the directory with the following:

```
node_modules/country-currency-map/
├── LICENSE
├── package.json
└── README.md

0 directories, 3 files
```

For now, we are cloning the content of this repository manually, but it will help if we can install all packages using the package.json file.

**Comment by dfenske** [comment]
![image](https://user-images.githubusercontent.com/4571750/75175565-6c24b300-56e7-11ea-8b85-62d2a31e5d47.png)
I am using the same node version, and I used `npm i country-currency` to install the package. Unfortunately I could not repro your problem. Are there any more details you can give me to help pinpoint the problem?

**Comment by ralphotowo** [comment]
Not really, it was happening while trying to package a node app into a Docker container. However, I've also reproduced the issue installing it to my Linux machine running v10.19 (see below)

![Screenshot from 2020-02-24 18-29-11](https://user-images.githubusercontent.com/1202767/75176073-be8bc100-5733-11ea-9ace-53e29776fd3d.png)

**Comment by dfenske** [comment]
Great to hear you resolved it! Sorry I can't help pinpoint the issue more. Thanks.
